import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: ['class', '[data-theme="dark"]'],
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        bg: 'var(--color-bg)',
        surface: 'var(--color-surface)',
        surfaceSoft: 'var(--color-surface-soft)',
        surfaceStrong: 'var(--color-surface-strong)',
        surfaceElevated: 'var(--color-surface-elevated)',
        panel: 'var(--color-panel)',
        cardSubtle: 'var(--color-card-subtle)',
        line: 'var(--color-line)',
        lineStrong: 'var(--color-line-strong)',
        ink: 'var(--color-ink)',
        inkStrong: 'var(--color-ink-strong)',
        mute: 'var(--color-mute)',
        muteStrong: 'var(--color-mute-strong)',
        accent: 'var(--color-accent)',
        accentSoft: 'var(--color-accent-soft)',
        accentInk: 'var(--color-accent-ink)',
        sidebar: 'var(--color-sidebar)',
        sidebarSoft: 'var(--color-sidebar-soft)',
        sidebarLine: 'var(--color-sidebar-line)',
        sidebarInk: 'var(--color-sidebar-ink)',
        topbar: 'var(--color-topbar)',
        danger: 'var(--color-danger)',
        dangerSoft: 'var(--color-danger-soft)',
        dangerLine: 'var(--color-danger-line)',
        dangerInk: 'var(--color-danger-ink)',
        warning: 'var(--color-warning)',
        warningSoft: 'var(--color-warning-soft)',
        warningLine: 'var(--color-warning-line)',
        warningInk: 'var(--color-warning-ink)',
        info: 'var(--color-info)',
        infoSoft: 'var(--color-info-soft)',
        infoLine: 'var(--color-info-line)',
        infoInk: 'var(--color-info-ink)',
        success: 'var(--color-success)',
        successSoft: 'var(--color-success-soft)',
        successLine: 'var(--color-success-line)',
        successInk: 'var(--color-success-ink)',
      },
      boxShadow: {
        panel: 'var(--shadow-panel)',
        card: 'var(--shadow-card)',
        soft: 'var(--shadow-soft)',
        focus: 'var(--shadow-focus)',
      },
      borderRadius: {
        xl2: '1rem',
        control: 'var(--radius-control)',
        surface: 'var(--radius-surface)',
        'surface-lg': 'var(--radius-surface-lg)',
        pill: 'var(--radius-pill)',
      },
      spacing: {
        micro: 'var(--space-micro)',
        compact: 'var(--space-compact)',
        comfort: 'var(--space-comfort)',
        section: 'var(--space-section)',
        page: 'var(--space-page)',
      },
      transitionDuration: {
        fast: '120ms',
        base: '160ms',
        slow: '220ms',
      },
      transitionTimingFunction: {
        'ui-standard': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [],
}

export default config
