version: '1'

build:
  method: direct
  engine: dockerfile
  disable_helper: true
  disable_buildx: true
  disable_buildkit: true
  helper_image: ghcr.io/coollabsio/coolify-helper:1.0.13
  buildkit_inline_cache: false
  nested_container: false
  docker_socket_build: true

deploy:
  restart: unless-stopped
  healthcheck_retries: 3
  healthcheck_start_period: 120
  healthcheck_interval: 300
  healthcheck_timeout: 10
