import { runReviewDbExecute, runReviewDbQuery } from '@/lib/review-db'

type ExecuteResult = {
  affectedRows?: number
}

type HrAuditActionType =
  | 'EMPLOYEE_CREATE'
  | 'EMPLOYEE_ARCHIVE'
  | 'EMPLOYEE_REACTIVATE'
  | 'EMPLOYEE_FACE_REFERENCE_UPSERT'
  | 'ATTENDANCE_CREATE'
  | 'ATTENDANCE_UPDATE'
  | 'ATTENDANCE_GEOFENCE_CONFIG'
  | 'ATTENDANCE_FACE_CONFIG'
  | 'ATTENDANCE_FACE_REVIEW'
  | 'ATTENDANCE_FACE_RETAKE_QUEUE'
  | 'LOAN_CREATE'
  | 'SALARY_SLIP_CREATE'
  | 'LOAN_UPDATE'
  | 'LOAN_VOID'
  | 'SALARY_SLIP_RELEASE'
  | 'SALARY_SLIP_VOID'
  | 'EMPLOYEE_UPDATE'
  | 'EMPLOYEE_HISTORY_EVENT'
  | 'EMPLOYEE_DOC_UPLOAD'
  | 'EMPLOYEE_DOC_DOWNLOAD'
  | 'EMPLOYEE_DOC_INACTIVE'
  | 'FP_DEVICE_CREATE'
  | 'FP_DEVICE_UPDATE'
  | 'FP_DEVICE_DELETE'
  | 'FP_MAP_EMPLOYEE'
  | 'ATTENDANCE_SYNC_SUCCESS'
  | 'ATTENDANCE_SYNC_PARTIAL'
  | 'ATTENDANCE_SYNC_FAILED'
  | 'ATTENDANCE_EXPORT'
  | 'EMPLOYEE_ATTENDANCE_CORRECTION'
  | 'ORG_TEAM_CREATE'
  | 'ORG_TEAM_UPDATE'
  | 'ORG_TEAM_DELETE'
  | 'ORG_POSITION_CREATE'
  | 'ORG_POSITION_UPDATE'
  | 'ORG_POSITION_DELETE'
  | 'SELF_DOC_DOWNLOAD'
  | 'LEAVE_TYPE_CREATE'
  | 'LEAVE_TYPE_UPDATE'
  | 'LEAVE_TYPE_DELETE'
  | 'LEAVE_BALANCE_ADJUST'
  | 'LEAVE_REQUEST_CREATE'
  | 'LEAVE_REQUEST_SUBMIT_SUPERVISOR'
  | 'LEAVE_REQUEST_SUPERVISOR_APPROVE'
  | 'LEAVE_REQUEST_SUPERVISOR_REJECT'
  | 'LEAVE_REQUEST_HR_APPROVE'
  | 'LEAVE_REQUEST_HR_REJECT'
  | 'LEAVE_REQUEST_CANCEL_EMPLOYEE'
  | 'LEAVE_REQUEST_HR_CANCEL'
  | 'LEAVE_REQUEST_HR_ATTENDANCE_APPLIED'
  | 'LEAVE_REVERT_CONFLICT'
  | 'OVERTIME_REQUEST_CREATE'
  | 'OVERTIME_REQUEST_SUBMIT'
  | 'OVERTIME_SUPERVISOR_APPROVE'
  | 'OVERTIME_SUPERVISOR_REJECT'
  | 'OVERTIME_HR_APPROVE'
  | 'OVERTIME_HR_REJECT'
  | 'OVERTIME_EMP_CANCEL'
  | 'OVERTIME_HR_CANCEL'
  | 'OVERTIME_HR_ATTENDANCE_APPLIED'
  | 'OVERTIME_REVERT_CONFLICT'
  | 'LEAVE_SUPERVISOR_SCOPE_VIOLATION'
  | 'OVERTIME_SUPERVISOR_SCOPE_VIOLATION'
  | 'LEAVE_IDOR_ATTEMPT'
  | 'OVERTIME_IDOR_ATTEMPT'

type HrAuditRow = {
  id: number
  actionType: string
  actorName: string | null
  targetRef: string | null
  detailText: string | null
  createdAt: string
}

export type HrAuditItem = {
  id: string
  actionType: HrAuditActionType
  actor: string
  targetRef: string
  detail: string
  happenedAt: string
}

let auditTableEnsured = false

export async function ensureHrAuditTable() {
  if (auditTableEnsured) {
    return
  }

  await runReviewDbExecute<ExecuteResult>(`
    CREATE TABLE IF NOT EXISTS hr_audit_logs (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      action_type ENUM('EMPLOYEE_CREATE','EMPLOYEE_ARCHIVE','EMPLOYEE_REACTIVATE','EMPLOYEE_FACE_REFERENCE_UPSERT','ATTENDANCE_CREATE','ATTENDANCE_UPDATE','ATTENDANCE_GEOFENCE_CONFIG','ATTENDANCE_FACE_CONFIG','ATTENDANCE_FACE_REVIEW','ATTENDANCE_FACE_RETAKE_QUEUE','LOAN_CREATE','SALARY_SLIP_CREATE','LOAN_UPDATE','LOAN_VOID','SALARY_SLIP_RELEASE','SALARY_SLIP_VOID','EMPLOYEE_UPDATE','EMPLOYEE_HISTORY_EVENT','EMPLOYEE_DOC_UPLOAD','EMPLOYEE_DOC_DOWNLOAD','EMPLOYEE_DOC_INACTIVE','FP_DEVICE_CREATE','FP_DEVICE_UPDATE','FP_DEVICE_DELETE','FP_MAP_EMPLOYEE','ATTENDANCE_SYNC_SUCCESS','ATTENDANCE_SYNC_PARTIAL','ATTENDANCE_SYNC_FAILED','ATTENDANCE_EXPORT','EMPLOYEE_ATTENDANCE_CORRECTION','ORG_TEAM_CREATE','ORG_TEAM_UPDATE','ORG_TEAM_DELETE','ORG_POSITION_CREATE','ORG_POSITION_UPDATE','ORG_POSITION_DELETE','SELF_DOC_DOWNLOAD','LEAVE_TYPE_CREATE','LEAVE_TYPE_UPDATE','LEAVE_TYPE_DELETE','LEAVE_BALANCE_ADJUST','LEAVE_REQUEST_CREATE','LEAVE_REQUEST_SUBMIT_SUPERVISOR','LEAVE_REQUEST_SUPERVISOR_APPROVE','LEAVE_REQUEST_SUPERVISOR_REJECT','LEAVE_REQUEST_HR_APPROVE','LEAVE_REQUEST_HR_REJECT','LEAVE_REQUEST_CANCEL_EMPLOYEE','LEAVE_REQUEST_HR_CANCEL','LEAVE_REQUEST_HR_ATTENDANCE_APPLIED','LEAVE_REVERT_CONFLICT','OVERTIME_REQUEST_CREATE','OVERTIME_REQUEST_SUBMIT','OVERTIME_SUPERVISOR_APPROVE','OVERTIME_SUPERVISOR_REJECT','OVERTIME_HR_APPROVE','OVERTIME_HR_REJECT','OVERTIME_EMP_CANCEL','OVERTIME_HR_CANCEL','OVERTIME_HR_ATTENDANCE_APPLIED','OVERTIME_REVERT_CONFLICT','LEAVE_SUPERVISOR_SCOPE_VIOLATION','OVERTIME_SUPERVISOR_SCOPE_VIOLATION','LEAVE_IDOR_ATTEMPT','OVERTIME_IDOR_ATTEMPT') NOT NULL,
      actor_name VARCHAR(150) NOT NULL,
      target_ref VARCHAR(180) NOT NULL,
      detail_text TEXT NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id),
      KEY idx_hr_audit_logs_created (created_at),
      KEY idx_hr_audit_logs_target (target_ref)
    )
  `)

  await runReviewDbExecute<ExecuteResult>(`
    ALTER TABLE hr_audit_logs
    MODIFY COLUMN action_type ENUM('EMPLOYEE_CREATE','EMPLOYEE_ARCHIVE','EMPLOYEE_REACTIVATE','EMPLOYEE_FACE_REFERENCE_UPSERT','ATTENDANCE_CREATE','ATTENDANCE_UPDATE','ATTENDANCE_GEOFENCE_CONFIG','ATTENDANCE_FACE_CONFIG','ATTENDANCE_FACE_REVIEW','ATTENDANCE_FACE_RETAKE_QUEUE','LOAN_CREATE','SALARY_SLIP_CREATE','LOAN_UPDATE','LOAN_VOID','SALARY_SLIP_RELEASE','SALARY_SLIP_VOID','EMPLOYEE_UPDATE','EMPLOYEE_HISTORY_EVENT','EMPLOYEE_DOC_UPLOAD','EMPLOYEE_DOC_DOWNLOAD','EMPLOYEE_DOC_INACTIVE','FP_DEVICE_CREATE','FP_DEVICE_UPDATE','FP_DEVICE_DELETE','FP_MAP_EMPLOYEE','ATTENDANCE_SYNC_SUCCESS','ATTENDANCE_SYNC_PARTIAL','ATTENDANCE_SYNC_FAILED','ATTENDANCE_EXPORT','EMPLOYEE_ATTENDANCE_CORRECTION','ORG_TEAM_CREATE','ORG_TEAM_UPDATE','ORG_TEAM_DELETE','ORG_POSITION_CREATE','ORG_POSITION_UPDATE','ORG_POSITION_DELETE','SELF_DOC_DOWNLOAD','LEAVE_TYPE_CREATE','LEAVE_TYPE_UPDATE','LEAVE_TYPE_DELETE','LEAVE_BALANCE_ADJUST','LEAVE_REQUEST_CREATE','LEAVE_REQUEST_SUBMIT_SUPERVISOR','LEAVE_REQUEST_SUPERVISOR_APPROVE','LEAVE_REQUEST_SUPERVISOR_REJECT','LEAVE_REQUEST_HR_APPROVE','LEAVE_REQUEST_HR_REJECT','LEAVE_REQUEST_CANCEL_EMPLOYEE','LEAVE_REQUEST_HR_CANCEL','LEAVE_REQUEST_HR_ATTENDANCE_APPLIED','LEAVE_REVERT_CONFLICT','OVERTIME_REQUEST_CREATE','OVERTIME_REQUEST_SUBMIT','OVERTIME_SUPERVISOR_APPROVE','OVERTIME_SUPERVISOR_REJECT','OVERTIME_HR_APPROVE','OVERTIME_HR_REJECT','OVERTIME_EMP_CANCEL','OVERTIME_HR_CANCEL','OVERTIME_HR_ATTENDANCE_APPLIED','OVERTIME_REVERT_CONFLICT','LEAVE_SUPERVISOR_SCOPE_VIOLATION','OVERTIME_SUPERVISOR_SCOPE_VIOLATION','LEAVE_IDOR_ATTEMPT','OVERTIME_IDOR_ATTEMPT') NOT NULL
  `)

  auditTableEnsured = true
}

function normalizeActionType(value: string): HrAuditActionType {
  const normalized = value.trim().toUpperCase()
  if (
    normalized === 'EMPLOYEE_CREATE' ||
    normalized === 'EMPLOYEE_ARCHIVE' ||
    normalized === 'EMPLOYEE_REACTIVATE' ||
    normalized === 'EMPLOYEE_FACE_REFERENCE_UPSERT' ||
    normalized === 'ATTENDANCE_CREATE' ||
    normalized === 'ATTENDANCE_UPDATE' ||
    normalized === 'ATTENDANCE_GEOFENCE_CONFIG' ||
    normalized === 'ATTENDANCE_FACE_CONFIG' ||
    normalized === 'ATTENDANCE_FACE_REVIEW' ||
    normalized === 'ATTENDANCE_FACE_RETAKE_QUEUE' ||
    normalized === 'LOAN_CREATE' ||
    normalized === 'SALARY_SLIP_CREATE' ||
    normalized === 'LOAN_UPDATE' ||
    normalized === 'LOAN_VOID' ||
    normalized === 'SALARY_SLIP_RELEASE' ||
    normalized === 'SALARY_SLIP_VOID' ||
    normalized === 'EMPLOYEE_UPDATE' ||
    normalized === 'EMPLOYEE_HISTORY_EVENT' ||
    normalized === 'EMPLOYEE_DOC_UPLOAD' ||
    normalized === 'EMPLOYEE_DOC_DOWNLOAD' ||
    normalized === 'EMPLOYEE_DOC_INACTIVE' ||
    normalized === 'FP_DEVICE_CREATE' ||
    normalized === 'FP_DEVICE_UPDATE' ||
    normalized === 'FP_DEVICE_DELETE' ||
    normalized === 'FP_MAP_EMPLOYEE' ||
    normalized === 'ATTENDANCE_SYNC_SUCCESS' ||
    normalized === 'ATTENDANCE_SYNC_PARTIAL' ||
    normalized === 'ATTENDANCE_SYNC_FAILED' ||
    normalized === 'ATTENDANCE_EXPORT' ||
    normalized === 'EMPLOYEE_ATTENDANCE_CORRECTION' ||
    normalized === 'ORG_TEAM_CREATE' ||
    normalized === 'ORG_TEAM_UPDATE' ||
    normalized === 'ORG_TEAM_DELETE' ||
    normalized === 'ORG_POSITION_CREATE' ||
    normalized === 'ORG_POSITION_UPDATE' ||
    normalized === 'ORG_POSITION_DELETE' ||
    normalized === 'SELF_DOC_DOWNLOAD' ||
    normalized === 'LEAVE_TYPE_CREATE' ||
    normalized === 'LEAVE_TYPE_UPDATE' ||
    normalized === 'LEAVE_TYPE_DELETE' ||
    normalized === 'LEAVE_BALANCE_ADJUST' ||
    normalized === 'LEAVE_REQUEST_CREATE' ||
    normalized === 'LEAVE_REQUEST_SUBMIT_SUPERVISOR' ||
    normalized === 'LEAVE_REQUEST_SUPERVISOR_APPROVE' ||
    normalized === 'LEAVE_REQUEST_SUPERVISOR_REJECT' ||
    normalized === 'LEAVE_REQUEST_HR_APPROVE' ||
    normalized === 'LEAVE_REQUEST_HR_REJECT' ||
    normalized === 'LEAVE_REQUEST_CANCEL_EMPLOYEE' ||
    normalized === 'LEAVE_REQUEST_HR_CANCEL' ||
    normalized === 'LEAVE_REQUEST_HR_ATTENDANCE_APPLIED' ||
    normalized === 'LEAVE_REVERT_CONFLICT' ||
    normalized === 'OVERTIME_REQUEST_CREATE' ||
    normalized === 'OVERTIME_REQUEST_SUBMIT' ||
    normalized === 'OVERTIME_SUPERVISOR_APPROVE' ||
    normalized === 'OVERTIME_SUPERVISOR_REJECT' ||
    normalized === 'OVERTIME_HR_APPROVE' ||
    normalized === 'OVERTIME_HR_REJECT' ||
    normalized === 'OVERTIME_EMP_CANCEL' ||
    normalized === 'OVERTIME_HR_CANCEL' ||
    normalized === 'OVERTIME_HR_ATTENDANCE_APPLIED' ||
    normalized === 'OVERTIME_REVERT_CONFLICT' ||
    normalized === 'LEAVE_SUPERVISOR_SCOPE_VIOLATION' ||
    normalized === 'OVERTIME_SUPERVISOR_SCOPE_VIOLATION' ||
    normalized === 'LEAVE_IDOR_ATTEMPT' ||
    normalized === 'OVERTIME_IDOR_ATTEMPT'
  ) {
    return normalized
  }

  return 'EMPLOYEE_CREATE'
}

export async function recordHrAudit(params: {
  actionType: HrAuditActionType
  actor: string
  targetRef: string
  detail: string
}) {
  await ensureHrAuditTable()

  await runReviewDbExecute<ExecuteResult>(
    `
      INSERT INTO hr_audit_logs (
        action_type,
        actor_name,
        target_ref,
        detail_text
      )
      VALUES (?, ?, ?, ?)
    `,
    [params.actionType, params.actor, params.targetRef, params.detail]
  )
}

export async function getRecentHrAudits(limit = 12): Promise<HrAuditItem[]> {
  await ensureHrAuditTable()

  const rows = await runReviewDbQuery<HrAuditRow>(
    `
      SELECT
        id,
        action_type AS actionType,
        actor_name AS actorName,
        target_ref AS targetRef,
        detail_text AS detailText,
        created_at AS createdAt
      FROM hr_audit_logs
      ORDER BY created_at DESC, id DESC
      LIMIT ?
    `,
    [limit]
  )

  return rows.map((row) => ({
    id: `hr-audit-${row.id}`,
    actionType: normalizeActionType(row.actionType),
    actor: row.actorName?.trim() || 'System Review',
    targetRef: row.targetRef?.trim() || '-',
    detail: row.detailText?.trim() || 'Aktivitas HR tercatat.',
    happenedAt: String(row.createdAt),
  }))
}
