import type { DeviceLifecycleLogRow } from '@/lib/services/device-lifecycle-service'
import type { NocQueueItem } from '@/lib/services/noc-queue-service'

export const mockTrackingWorkOrders = [
  {
    id: 321,
    workOrderNo: 'WO-202607-0321',
    workType: 'FIELD_VISIT',
    jobCategory: 'TROUBLE',
    status: 'ON_PROGRESS',
    priority: 'HIGH',
    scheduledAt: '2026-07-19 09:30:00',
    technicianName: 'Team Troubleshoots Barat',
    troubleTicketId: 12,
    salesOrderId: null,
    subscriptionId: 880012,
    picUserId: 44,
    picUsername: 'support.ops',
    picFullName: 'Operator NOC Support',
    notes: 'Pergantian ONT untuk pelanggan LOS. Modem lama perlu dicapture sebagai replace.',
    createdAt: '2026-07-19 08:10:00',
    updatedAt: '2026-07-19 10:25:00',
  },
  {
    id: 322,
    workOrderNo: 'WO-202607-0322',
    workType: 'INSTALLATION',
    jobCategory: 'PSB',
    status: 'OPEN',
    priority: 'MEDIUM',
    scheduledAt: '2026-07-19 13:00:00',
    technicianName: 'Team PSB Timur',
    troubleTicketId: null,
    salesOrderId: 550021,
    subscriptionId: 880045,
    picUserId: 44,
    picUsername: 'support.ops',
    picFullName: 'Operator NOC Support',
    notes: 'Instalasi baru pelanggan PSB dengan ONT siap delegasi ke teknisi.',
    createdAt: '2026-07-19 08:45:00',
    updatedAt: '2026-07-19 09:40:00',
  },
]

export const mockTrackingWorkOrderAssignments = [
  {
    id: 9001,
    workOrderId: 321,
    assignedUserId: 211,
    assignmentRole: 'FIELD_TECHNICIAN',
    assignmentStatus: 'ACCEPTED',
    isPrimary: 1,
    assignedAt: '2026-07-19 08:20:00',
    acceptedAt: '2026-07-19 08:28:00',
    releasedAt: null,
    notes: 'Teknisi trouble menerima ticket untuk replacement ONT.',
    assignedUsername: 'teknisi.trouble01',
    assignedFullName: 'Teknisi Trouble 01',
  },
  {
    id: 9002,
    workOrderId: 322,
    assignedUserId: 212,
    assignmentRole: 'FIELD_TECHNICIAN',
    assignmentStatus: 'ASSIGNED',
    isPrimary: 1,
    assignedAt: '2026-07-19 09:10:00',
    acceptedAt: null,
    releasedAt: null,
    notes: 'Delegasi awal instalasi PSB.',
    assignedUsername: 'teknisi.psb01',
    assignedFullName: 'Teknisi PSB 01',
  },
]

export const mockTrackingWorkOrderStatusLogs = [
  {
    id: 9101,
    workOrderId: 321,
    fromStatus: 'OPEN',
    toStatus: 'ON_PROGRESS',
    reasonCode: 'NOC_DISPATCH',
    reasonNotes: 'NOC dispatch ke tim trouble untuk pengecekan LOS dan replace ONT.',
    changedByUserId: 44,
    changedAt: '2026-07-19 08:18:00',
  },
  {
    id: 9102,
    workOrderId: 322,
    fromStatus: 'DRAFT',
    toStatus: 'OPEN',
    reasonCode: 'PSB_READY',
    reasonNotes: 'WO PSB siap dijadwalkan setelah ONT lolos cek NOC.',
    changedByUserId: 44,
    changedAt: '2026-07-19 08:55:00',
  },
]

export const mockTrackingTroubleTickets = [
  {
    id: 12,
    branchId: 7,
    subscriptionId: 880012,
    ticketCode: 'TT-202607-0012',
    customerName: 'PT Sinar Fiber',
    customerUser: 'SUB-880012',
    category: 'TT',
    type: 'LOS',
    status: 'ON_PROGRESS',
    problemCategory: 'ONT LOS',
    resolutionAction: 'ONT replacement dan validasi NOC',
    notes: 'Pelanggan mengalami LOS sejak pagi. ONT lama perlu diganti unit baru.',
    closeNotes: null,
    openedAt: '2026-07-19 07:55:00',
    closedAt: null,
    createdAt: '2026-07-19 07:55:00',
    updatedAt: '2026-07-19 10:30:00',
  },
]

export const mockTrackingInventoryRequests = [
  {
    id: 88,
    requestCode: 'REQ-202607-0088',
    inventoryItemId: 701,
    itemCode: 'INV-ONT-202607-0001',
    itemName: 'ONT ZTE F670L',
    requestQty: 1,
    requestType: 'WO_MATERIAL',
    requestStatus: 'APPROVED',
    requestedDivision: 'FIELD OPS',
    requestedSubdivision: 'TEAM PSB TIMUR',
    requestedFor: 'Team PSB Timur',
    requestNotes: 'Request ONT PSB untuk instalasi pelanggan baru setelah lolos cek NOC.',
    pendingReason: null,
    requestedBy: 'support.ops',
    processedBy: 'admin.inventory',
    requestedAt: '2026-07-19 08:52:00',
    processedAt: '2026-07-19 09:00:00',
    completedAt: null,
    workOrderId: 322,
    troubleTicketId: null,
  },
  {
    id: 87,
    requestCode: 'REQ-202607-0087',
    inventoryItemId: 702,
    itemCode: 'INV-ONT-202607-0002',
    itemName: 'ONT Huawei HG8245H',
    requestQty: 1,
    requestType: 'TROUBLE_SUPPORT',
    requestStatus: 'PICKED',
    requestedDivision: 'FIELD OPS',
    requestedSubdivision: 'TEAM TROUBLESHOOTS BARAT',
    requestedFor: 'Team Troubleshoots Barat',
    requestNotes: 'Request ONT pengganti untuk kasus LOS pelanggan area barat.',
    pendingReason: null,
    requestedBy: 'support.ops',
    processedBy: 'admin.inventory',
    requestedAt: '2026-07-19 08:58:00',
    processedAt: '2026-07-19 09:12:00',
    completedAt: null,
    workOrderId: 321,
    troubleTicketId: 12,
  },
]

export const mockTrackingStockMovements = [
  {
    id: 8101,
    itemId: 701,
    itemCode: 'INV-ONT-202607-0001',
    itemName: 'ONT ZTE F670L',
    movementType: 'OUT',
    referenceType: 'WORK_ORDER',
    referenceNo: 'WO-202607-0322',
    qty: 1,
    unitPrice: 375000,
    movementStatus: 'PICKED',
    workOrderId: 322,
    troubleTicketId: null,
    requestId: 88,
    fromLocationId: 10,
    toLocationId: 21,
    technicianUserId: 212,
    technicianUsername: 'teknisi.psb01',
    technicianFullName: 'Teknisi PSB 01',
    fromLocationCode: 'GA-STOCK',
    fromLocationName: 'Gudang GA',
    toLocationCode: 'NOC-BENCH',
    toLocationName: 'Meja Cek NOC',
    notes: 'ONT PSB keluar dari gudang untuk proses check-in NOC.',
    movementAt: '2026-07-19 09:05:00',
  },
  {
    id: 8102,
    itemId: 702,
    itemCode: 'INV-ONT-202607-0002',
    itemName: 'ONT Huawei HG8245H',
    movementType: 'OUT',
    referenceType: 'TROUBLE_TICKET',
    referenceNo: 'TT-202607-0012',
    qty: 1,
    unitPrice: 410000,
    movementStatus: 'IN_TRANSIT',
    workOrderId: 321,
    troubleTicketId: 12,
    requestId: 87,
    fromLocationId: 21,
    toLocationId: 31,
    technicianUserId: 211,
    technicianUsername: 'teknisi.trouble01',
    technicianFullName: 'Teknisi Trouble 01',
    fromLocationCode: 'NOC-BENCH',
    fromLocationName: 'Meja Cek NOC',
    toLocationCode: 'FIELD-BARAT',
    toLocationName: 'Area Barat',
    notes: 'ONT pengganti sedang dibawa teknisi trouble ke lokasi pelanggan.',
    movementAt: '2026-07-19 09:22:00',
  },
  {
    id: 8103,
    itemId: 703,
    itemCode: 'INV-ONT-202601-0444',
    itemName: 'ONT Fiberhome AN5506',
    movementType: 'IN',
    referenceType: 'TROUBLE_TICKET',
    referenceNo: 'TT-202607-0012',
    qty: 1,
    unitPrice: 0,
    movementStatus: 'RETURNED',
    workOrderId: 321,
    troubleTicketId: 12,
    requestId: null,
    fromLocationId: 31,
    toLocationId: 21,
    technicianUserId: 211,
    technicianUsername: 'teknisi.trouble01',
    technicianFullName: 'Teknisi Trouble 01',
    fromLocationCode: 'FIELD-BARAT',
    fromLocationName: 'Area Barat',
    toLocationCode: 'NOC-BENCH',
    toLocationName: 'Meja Cek NOC',
    notes: 'ONT lama dikembalikan untuk validasi kerusakan.',
    movementAt: '2026-07-19 10:05:00',
  },
]

export const mockTrackingDeviceLifecycleLogs: DeviceLifecycleLogRow[] = [
  {
    id: 12005,
    inventoryItemId: 702,
    itemCode: 'INV-ONT-202607-0002',
    itemName: 'ONT Huawei HG8245H',
    relatedInventoryItemId: 703,
    relatedItemCode: 'INV-ONT-202601-0444',
    relatedItemName: 'ONT Fiberhome AN5506',
    workOrderId: 321,
    troubleTicketId: 12,
    ticketType: 'TROUBLESHOOTS',
    ticketRef: 'TT-202607-0012',
    lifecycleStatus: 'PENDING_NOC_VALIDATION',
    fromStatus: 'REPLACE_NEW',
    eventType: 'TECHNICIAN_SCAN',
    scanSource: 'BARCODE_SCANNER',
    targetTeam: 'Team Troubleshoots Barat',
    locationCode: 'SITE-BARAT',
    locationName: 'Rumah Pelanggan Area Barat',
    validationStatus: 'PENDING',
    handoverFromLabel: 'Teknisi Trouble 01',
    handoverToLabel: 'NOC Support',
    handoverProofType: 'BARCODE_SCAN',
    handoverProofRef: 'HO-TT-0012-05',
    notes: 'ONT baru terpasang dan menunggu validasi NOC.',
    actorUserId: 211,
    actorName: 'Teknisi Trouble 01',
    actorRole: 'FIELD_TECHNICIAN',
    createdAt: '2026-07-19 10:15:00',
  },
  {
    id: 12004,
    inventoryItemId: 702,
    itemCode: 'INV-ONT-202607-0002',
    itemName: 'ONT Huawei HG8245H',
    relatedInventoryItemId: 703,
    relatedItemCode: 'INV-ONT-202601-0444',
    relatedItemName: 'ONT Fiberhome AN5506',
    workOrderId: 321,
    troubleTicketId: 12,
    ticketType: 'TROUBLESHOOTS',
    ticketRef: 'TT-202607-0012',
    lifecycleStatus: 'REPLACE_NEW',
    fromStatus: 'REPLACE_OLD',
    eventType: 'REPLACE_NEW_PREPARED',
    scanSource: 'BARCODE_SCANNER',
    targetTeam: 'Team Troubleshoots Barat',
    locationCode: 'FIELD-BARAT',
    locationName: 'Area Barat',
    validationStatus: 'NOT_REQUIRED',
    handoverFromLabel: 'NOC Support',
    handoverToLabel: 'Teknisi Trouble 01',
    handoverProofType: 'SERIAL_CHECK',
    handoverProofRef: 'HO-TT-0012-04',
    notes: 'ONT pengganti disiapkan untuk replacement.',
    actorUserId: 44,
    actorName: 'Operator NOC Support',
    actorRole: 'NOC_OPERATOR',
    createdAt: '2026-07-19 09:24:00',
  },
  {
    id: 12003,
    inventoryItemId: 703,
    itemCode: 'INV-ONT-202601-0444',
    itemName: 'ONT Fiberhome AN5506',
    relatedInventoryItemId: 702,
    relatedItemCode: 'INV-ONT-202607-0002',
    relatedItemName: 'ONT Huawei HG8245H',
    workOrderId: 321,
    troubleTicketId: 12,
    ticketType: 'TROUBLESHOOTS',
    ticketRef: 'TT-202607-0012',
    lifecycleStatus: 'REPLACE_OLD',
    fromStatus: 'TEAM_TROUBLESHOOTS',
    eventType: 'REPLACE_OLD_CAPTURED',
    scanSource: 'BARCODE_SCANNER',
    targetTeam: 'Team Troubleshoots Barat',
    locationCode: 'SITE-BARAT',
    locationName: 'Rumah Pelanggan Area Barat',
    validationStatus: 'NOT_REQUIRED',
    handoverFromLabel: 'Pelanggan',
    handoverToLabel: 'Teknisi Trouble 01',
    handoverProofType: 'MANUAL_CONFIRMATION',
    handoverProofRef: 'HO-TT-0012-03',
    notes: 'ONT lama rusak dicapture untuk replacement.',
    actorUserId: 211,
    actorName: 'Teknisi Trouble 01',
    actorRole: 'FIELD_TECHNICIAN',
    createdAt: '2026-07-19 09:58:00',
  },
  {
    id: 12002,
    inventoryItemId: 702,
    itemCode: 'INV-ONT-202607-0002',
    itemName: 'ONT Huawei HG8245H',
    relatedInventoryItemId: null,
    relatedItemCode: null,
    relatedItemName: null,
    workOrderId: 321,
    troubleTicketId: 12,
    ticketType: 'TROUBLESHOOTS',
    ticketRef: 'WO-202607-0321',
    lifecycleStatus: 'TEAM_TROUBLESHOOTS',
    fromStatus: 'NOC',
    eventType: 'TECHNICIAN_DELEGATION',
    scanSource: 'BARCODE_SCANNER',
    targetTeam: 'Team Troubleshoots Barat',
    locationCode: 'FIELD-BARAT',
    locationName: 'Area Barat',
    validationStatus: 'NOT_REQUIRED',
    handoverFromLabel: 'NOC Support',
    handoverToLabel: 'Teknisi Trouble 01',
    handoverProofType: 'BARCODE_SCAN',
    handoverProofRef: 'HO-TT-0012-02',
    notes: 'ONT didelegasikan ke teknisi trouble.',
    actorUserId: 44,
    actorName: 'Operator NOC Support',
    actorRole: 'NOC_OPERATOR',
    createdAt: '2026-07-19 09:20:00',
  },
  {
    id: 12001,
    inventoryItemId: 702,
    itemCode: 'INV-ONT-202607-0002',
    itemName: 'ONT Huawei HG8245H',
    relatedInventoryItemId: null,
    relatedItemCode: null,
    relatedItemName: null,
    workOrderId: 321,
    troubleTicketId: 12,
    ticketType: 'TROUBLESHOOTS',
    ticketRef: 'TT-202607-0012',
    lifecycleStatus: 'NOC',
    fromStatus: 'INVENTORY',
    eventType: 'NOC_CHECKIN',
    scanSource: 'BARCODE_SCANNER',
    targetTeam: null,
    locationCode: 'NOC-BENCH',
    locationName: 'Meja Cek NOC',
    validationStatus: 'NOT_REQUIRED',
    handoverFromLabel: 'Gudang GA',
    handoverToLabel: 'NOC Support',
    handoverProofType: 'BARCODE_SCAN',
    handoverProofRef: 'HO-TT-0012-01',
    notes: 'ONT pengganti lolos pengecekan awal NOC.',
    actorUserId: 44,
    actorName: 'Operator NOC Support',
    actorRole: 'NOC_OPERATOR',
    createdAt: '2026-07-19 09:05:00',
  },
  {
    id: 12103,
    inventoryItemId: 701,
    itemCode: 'INV-ONT-202607-0001',
    itemName: 'ONT ZTE F670L',
    relatedInventoryItemId: null,
    relatedItemCode: null,
    relatedItemName: null,
    workOrderId: 322,
    troubleTicketId: null,
    ticketType: 'PSB',
    ticketRef: 'WO-202607-0322',
    lifecycleStatus: 'TEAM_PSB',
    fromStatus: 'NOC',
    eventType: 'TECHNICIAN_DELEGATION',
    scanSource: 'BARCODE_SCANNER',
    targetTeam: 'Team PSB Timur',
    locationCode: 'PSB-EAST',
    locationName: 'Area PSB Timur',
    validationStatus: 'NOT_REQUIRED',
    handoverFromLabel: 'NOC Support',
    handoverToLabel: 'Teknisi PSB 01',
    handoverProofType: 'BARCODE_SCAN',
    handoverProofRef: 'HO-WO-0322-03',
    notes: 'ONT PSB diserahkan ke teknisi pemasangan.',
    actorUserId: 44,
    actorName: 'Operator NOC Support',
    actorRole: 'NOC_OPERATOR',
    createdAt: '2026-07-19 09:40:00',
  },
  {
    id: 12102,
    inventoryItemId: 701,
    itemCode: 'INV-ONT-202607-0001',
    itemName: 'ONT ZTE F670L',
    relatedInventoryItemId: null,
    relatedItemCode: null,
    relatedItemName: null,
    workOrderId: 322,
    troubleTicketId: null,
    ticketType: 'PSB',
    ticketRef: 'WO-202607-0322',
    lifecycleStatus: 'NOC',
    fromStatus: 'INVENTORY',
    eventType: 'NOC_CHECKIN',
    scanSource: 'BARCODE_SCANNER',
    targetTeam: null,
    locationCode: 'NOC-BENCH',
    locationName: 'Meja Cek NOC',
    validationStatus: 'NOT_REQUIRED',
    handoverFromLabel: 'Gudang GA',
    handoverToLabel: 'NOC Support',
    handoverProofType: 'SERIAL_CHECK',
    handoverProofRef: 'HO-WO-0322-02',
    notes: 'ONT baru selesai dicek dan siap dipakai PSB.',
    actorUserId: 44,
    actorName: 'Operator NOC Support',
    actorRole: 'NOC_OPERATOR',
    createdAt: '2026-07-19 09:20:00',
  },
  {
    id: 12101,
    inventoryItemId: 701,
    itemCode: 'INV-ONT-202607-0001',
    itemName: 'ONT ZTE F670L',
    relatedInventoryItemId: null,
    relatedItemCode: null,
    relatedItemName: null,
    workOrderId: 322,
    troubleTicketId: null,
    ticketType: 'PSB',
    ticketRef: 'WO-202607-0322',
    lifecycleStatus: 'INVENTORY',
    fromStatus: null,
    eventType: 'INVENTORY_INPUT',
    scanSource: 'MANUAL',
    targetTeam: null,
    locationCode: 'GA-STOCK',
    locationName: 'Gudang GA',
    validationStatus: 'NOT_REQUIRED',
    handoverFromLabel: null,
    handoverToLabel: null,
    handoverProofType: null,
    handoverProofRef: null,
    notes: 'Barang masuk dan barcode berhasil digenerate.',
    actorUserId: 15,
    actorName: 'Admin Inventory',
    actorRole: 'GA',
    createdAt: '2026-07-19 08:48:00',
  },
]

export const mockTrackingNocQueueItems: NocQueueItem[] = [
  {
    queueKey: 'WO-322',
    sourceType: 'WORK_ORDER',
    sourceId: 322,
    ticketNo: 'WO-202607-0322',
    ticketType: 'PSB',
    queueStatus: 'OPEN',
    rawStatus: 'OPEN',
    customerName: 'CV Pasang Baru Timur',
    customerUser: 'SUB-880045',
    workOrderId: 322,
    troubleTicketId: null,
    priority: 'MEDIUM',
    technicianName: 'Team PSB Timur',
    picName: 'Operator NOC Support',
    picUsername: 'support.ops',
    supportLaneLabel: 'Lane PSB',
    requestCode: 'REQ-PSB-0322',
    requestStatus: 'APPROVED',
    requestRequestedFor: 'PSB',
    deviceState: 'Barang siap delegasi ke Team PSB',
    deviceLifecycleStatus: 'TEAM_PSB',
    deviceValidationStatus: 'NOT_REQUIRED',
    deviceTicketRef: 'WO-202607-0322',
    deviceHandoverFrom: 'NOC Support',
    deviceHandoverTo: 'Teknisi PSB 01',
    deviceHandoverProofType: 'BARCODE_SCAN',
    deviceHandoverProofRef: 'HO-WO-0322-03',
    deviceItemLabel: 'INV-ONT-202607-0001 | ONT ZTE F670L',
    deviceLocationLabel: 'Area PSB Timur',
    deviceLastActor: 'Operator NOC Support',
    queueStartedAt: '2026-07-19 08:45:00',
    ageHours: 2,
    ageLabel: '2 jam',
    slaState: 'ON_TRACK',
    slaLabel: 'Masih dalam SLA',
    operationalBadges: ['PSB', 'LIFECYCLE AKTIF'],
    lastUpdateAt: '2026-07-19 09:40:00',
    href: '/dashboard/tracking/work-orders/322',
  },
  {
    queueKey: 'TT-12',
    sourceType: 'TROUBLE_TICKET',
    sourceId: 12,
    ticketNo: 'TT-202607-0012',
    ticketType: 'TROUBLESHOOTS',
    queueStatus: 'ON_PROGRESS',
    rawStatus: 'ON_PROGRESS',
    customerName: 'PT Sinar Fiber',
    customerUser: 'SUB-880012',
    workOrderId: 321,
    troubleTicketId: 12,
    priority: 'HIGH',
    technicianName: 'Team Troubleshoots Barat',
    picName: 'Operator NOC Support',
    picUsername: 'support.ops',
    supportLaneLabel: 'Lane Troubleshoots',
    requestCode: 'REQ-TT-0012',
    requestStatus: 'PICKING',
    requestRequestedFor: 'Troubleshoots',
    deviceState: 'Menunggu validasi NOC setelah replacement',
    deviceLifecycleStatus: 'PENDING_NOC_VALIDATION',
    deviceValidationStatus: 'PENDING',
    deviceTicketRef: 'TT-202607-0012',
    deviceHandoverFrom: 'Teknisi Trouble 01',
    deviceHandoverTo: 'NOC Support',
    deviceHandoverProofType: 'BARCODE_SCAN',
    deviceHandoverProofRef: 'HO-TT-0012-05',
    deviceItemLabel: 'INV-ONT-202607-0002 | ONT Huawei HG8245H',
    deviceLocationLabel: 'Rumah Pelanggan Area Barat',
    deviceLastActor: 'Teknisi Trouble 01',
    queueStartedAt: '2026-07-19 07:55:00',
    ageHours: 3,
    ageLabel: '3 jam',
    slaState: 'WARNING',
    slaLabel: 'Mendekati SLA',
    operationalBadges: ['REPLACE', 'PENDING VALIDASI', 'LOS'],
    lastUpdateAt: '2026-07-19 10:15:00',
    href: '/dashboard/tracking/trouble-tickets/12',
  },
]

export const mockTrackingItemSuggestions: string[] = [
  'INV-ONT-202607-0001 | ONT ZTE F670L',
  'INV-ONT-202607-0002 | ONT Huawei HG8245H',
  'INV-ONT-202601-0444 | ONT Fiberhome AN5506',
]
