-- Jalankan file ini setelah `xampp_review_schema.sql` dan `xampp_review_schema_phase_1_1.sql`
-- Tabel staging dipakai untuk menampung data mentah dari sistem lama sebelum dipetakan ke tabel final.

USE erp_isp_review;

CREATE TABLE IF NOT EXISTS staging_import_batches (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_code VARCHAR(50) NOT NULL,
  source_system ENUM('WEB_PSB','FINANCE','GA') NOT NULL,
  import_scope VARCHAR(100) NOT NULL,
  source_file_name VARCHAR(255) NULL,
  import_status ENUM('DRAFT','UPLOADED','MAPPED','VALIDATED','IMPORTED','FAILED') NOT NULL DEFAULT 'DRAFT',
  total_rows INT NOT NULL DEFAULT 0,
  valid_rows INT NOT NULL DEFAULT 0,
  invalid_rows INT NOT NULL DEFAULT 0,
  duplicate_rows INT NOT NULL DEFAULT 0,
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_staging_import_batches_code (batch_code)
);

CREATE TABLE IF NOT EXISTS staging_import_batch_actions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  action_type ENUM('CREATE','UPLOAD','VALIDATE','TRANSFORM') NOT NULL,
  action_status ENUM('SUCCESS','FAILED','INFO') NOT NULL DEFAULT 'INFO',
  actor_name VARCHAR(150) NULL,
  detail_text TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_staging_import_batch_actions_batch (batch_id),
  CONSTRAINT fk_staging_import_batch_actions_batch FOREIGN KEY (batch_id) REFERENCES staging_import_batches(id)
);

CREATE TABLE IF NOT EXISTS staging_legacy_user_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  source_system ENUM('WEB_PSB','FINANCE','GA') NOT NULL,
  legacy_id VARCHAR(100) NULL,
  legacy_role VARCHAR(100) NULL,
  legacy_division VARCHAR(100) NULL,
  full_name VARCHAR(150) NULL,
  username VARCHAR(100) NULL,
  email VARCHAR(150) NULL,
  phone VARCHAR(30) NULL,
  employee_legacy_id VARCHAR(100) NULL,
  raw_payload LONGTEXT NULL,
  normalized_key VARCHAR(180) NULL,
  mapped_role_code VARCHAR(50) NULL,
  mapped_division_code VARCHAR(30) NULL,
  target_user_id BIGINT UNSIGNED NULL,
  import_status ENUM('PENDING','MAPPED','VALID','INVALID','IMPORTED','SKIPPED') NOT NULL DEFAULT 'PENDING',
  validation_notes TEXT NULL,
  imported_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_staging_legacy_user_batch (batch_id),
  KEY idx_staging_legacy_user_target (target_user_id),
  CONSTRAINT fk_staging_legacy_user_batch FOREIGN KEY (batch_id) REFERENCES staging_import_batches(id),
  CONSTRAINT fk_staging_legacy_user_target FOREIGN KEY (target_user_id) REFERENCES auth_users(id)
);

CREATE TABLE IF NOT EXISTS staging_legacy_customer_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  source_system ENUM('WEB_PSB') NOT NULL DEFAULT 'WEB_PSB',
  legacy_id VARCHAR(100) NULL,
  customer_name VARCHAR(150) NULL,
  customer_type VARCHAR(50) NULL,
  phone VARCHAR(30) NULL,
  email VARCHAR(150) NULL,
  identity_no VARCHAR(50) NULL,
  address_text TEXT NULL,
  maps_url TEXT NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  marketing_name VARCHAR(120) NULL,
  branch_code VARCHAR(30) NULL,
  raw_payload LONGTEXT NULL,
  normalized_key VARCHAR(180) NULL,
  target_customer_id BIGINT UNSIGNED NULL,
  target_address_id BIGINT UNSIGNED NULL,
  import_status ENUM('PENDING','MAPPED','VALID','INVALID','IMPORTED','SKIPPED') NOT NULL DEFAULT 'PENDING',
  validation_notes TEXT NULL,
  imported_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_staging_legacy_customer_batch (batch_id),
  KEY idx_staging_legacy_customer_target (target_customer_id),
  CONSTRAINT fk_staging_legacy_customer_batch FOREIGN KEY (batch_id) REFERENCES staging_import_batches(id),
  CONSTRAINT fk_staging_legacy_customer_target FOREIGN KEY (target_customer_id) REFERENCES crm_customers(id),
  CONSTRAINT fk_staging_legacy_customer_target_address FOREIGN KEY (target_address_id) REFERENCES crm_customer_addresses(id)
);

CREATE TABLE IF NOT EXISTS staging_legacy_order_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  source_system ENUM('WEB_PSB') NOT NULL DEFAULT 'WEB_PSB',
  legacy_id VARCHAR(100) NULL,
  legacy_customer_id VARCHAR(100) NULL,
  legacy_package_name VARCHAR(150) NULL,
  order_no VARCHAR(50) NULL,
  order_type VARCHAR(50) NULL,
  order_status VARCHAR(50) NULL,
  request_date DATETIME NULL,
  scheduled_installation_at DATETIME NULL,
  installed_date DATETIME NULL,
  marketing_name VARCHAR(120) NULL,
  teknisi_name VARCHAR(120) NULL,
  location_map TEXT NULL,
  notes TEXT NULL,
  raw_payload LONGTEXT NULL,
  normalized_key VARCHAR(180) NULL,
  mapped_package_code VARCHAR(50) NULL,
  target_customer_id BIGINT UNSIGNED NULL,
  target_order_id BIGINT UNSIGNED NULL,
  target_subscription_id BIGINT UNSIGNED NULL,
  target_work_order_id BIGINT UNSIGNED NULL,
  import_status ENUM('PENDING','MAPPED','VALID','INVALID','IMPORTED','SKIPPED') NOT NULL DEFAULT 'PENDING',
  validation_notes TEXT NULL,
  imported_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_staging_legacy_order_batch (batch_id),
  KEY idx_staging_legacy_order_target_order (target_order_id),
  CONSTRAINT fk_staging_legacy_order_batch FOREIGN KEY (batch_id) REFERENCES staging_import_batches(id),
  CONSTRAINT fk_staging_legacy_order_target_customer FOREIGN KEY (target_customer_id) REFERENCES crm_customers(id),
  CONSTRAINT fk_staging_legacy_order_target_order FOREIGN KEY (target_order_id) REFERENCES sales_orders(id),
  CONSTRAINT fk_staging_legacy_order_target_subscription FOREIGN KEY (target_subscription_id) REFERENCES service_subscriptions(id),
  CONSTRAINT fk_staging_legacy_order_target_work_order FOREIGN KEY (target_work_order_id) REFERENCES service_work_orders(id)
);

CREATE TABLE IF NOT EXISTS staging_legacy_support_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  source_system ENUM('WEB_PSB') NOT NULL DEFAULT 'WEB_PSB',
  support_type ENUM('TROUBLE_TICKET','ISOLATION','DISMANTLE_HISTORY','DISMANTLE_QUEUE','TROUBLE_TICKET_PHOTO','TROUBLE_TICKET_SLA','TROUBLE_TICKET_MASTER') NOT NULL,
  legacy_id VARCHAR(100) NULL,
  legacy_customer_id VARCHAR(100) NULL,
  legacy_parent_id VARCHAR(100) NULL,
  legacy_reference_code VARCHAR(100) NULL,
  ticket_code VARCHAR(50) NULL,
  customer_name VARCHAR(150) NULL,
  customer_address TEXT NULL,
  customer_phone VARCHAR(30) NULL,
  customer_user VARCHAR(150) NULL,
  marketing_name VARCHAR(120) NULL,
  radbox_name VARCHAR(120) NULL,
  category VARCHAR(30) NULL,
  trouble_type VARCHAR(100) NULL,
  support_status VARCHAR(50) NULL,
  opened_at DATETIME NULL,
  closed_at DATETIME NULL,
  reason_text TEXT NULL,
  note_text TEXT NULL,
  actor_name VARCHAR(150) NULL,
  problem_category VARCHAR(120) NULL,
  resolution_action VARCHAR(120) NULL,
  photo_list_text LONGTEXT NULL,
  raw_payload LONGTEXT NULL,
  normalized_key VARCHAR(180) NULL,
  target_subscription_id BIGINT UNSIGNED NULL,
  target_trouble_ticket_id BIGINT UNSIGNED NULL,
  target_isolation_id BIGINT UNSIGNED NULL,
  target_dismantle_history_id BIGINT UNSIGNED NULL,
  target_dismantle_queue_id BIGINT UNSIGNED NULL,
  target_trouble_ticket_sla_id BIGINT UNSIGNED NULL,
  import_status ENUM('PENDING','MAPPED','VALID','INVALID','IMPORTED','SKIPPED') NOT NULL DEFAULT 'PENDING',
  validation_notes TEXT NULL,
  imported_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_staging_legacy_support_batch (batch_id),
  CONSTRAINT fk_staging_legacy_support_batch FOREIGN KEY (batch_id) REFERENCES staging_import_batches(id),
  CONSTRAINT fk_staging_legacy_support_target_subscription FOREIGN KEY (target_subscription_id) REFERENCES service_subscriptions(id),
  CONSTRAINT fk_staging_legacy_support_target_ticket FOREIGN KEY (target_trouble_ticket_id) REFERENCES support_trouble_tickets(id),
  CONSTRAINT fk_staging_legacy_support_target_isolation FOREIGN KEY (target_isolation_id) REFERENCES support_isolations(id),
  CONSTRAINT fk_staging_legacy_support_target_dismantle FOREIGN KEY (target_dismantle_history_id) REFERENCES support_dismantle_history(id),
  CONSTRAINT fk_staging_legacy_support_target_dismantle_queue FOREIGN KEY (target_dismantle_queue_id) REFERENCES support_dismantle_queue(id),
  CONSTRAINT fk_staging_legacy_support_target_ticket_sla FOREIGN KEY (target_trouble_ticket_sla_id) REFERENCES support_trouble_ticket_sla(id)
);

CREATE TABLE IF NOT EXISTS staging_legacy_billing_invoice_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  source_system ENUM('WEB_PSB') NOT NULL DEFAULT 'WEB_PSB',
  legacy_id VARCHAR(100) NULL,
  legacy_customer_id VARCHAR(100) NULL,
  legacy_subscription_ref VARCHAR(100) NULL,
  invoice_no VARCHAR(50) NULL,
  invoice_type VARCHAR(50) NULL,
  billing_month TINYINT UNSIGNED NULL,
  billing_year SMALLINT UNSIGNED NULL,
  period_start DATE NULL,
  period_end DATE NULL,
  issue_date DATE NULL,
  due_date DATE NULL,
  subtotal DECIMAL(15,2) NULL,
  penalty_amount DECIMAL(15,2) NULL,
  discount_amount DECIMAL(15,2) NULL,
  total_amount DECIMAL(15,2) NULL,
  paid_amount DECIMAL(15,2) NULL,
  invoice_status VARCHAR(50) NULL,
  collection_status VARCHAR(50) NULL,
  suspend_candidate TINYINT(1) NULL,
  notes TEXT NULL,
  raw_payload LONGTEXT NULL,
  normalized_key VARCHAR(180) NULL,
  target_subscription_id BIGINT UNSIGNED NULL,
  target_invoice_id BIGINT UNSIGNED NULL,
  import_status ENUM('PENDING','MAPPED','VALID','INVALID','IMPORTED','SKIPPED') NOT NULL DEFAULT 'PENDING',
  validation_notes TEXT NULL,
  imported_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_staging_legacy_billing_invoice_batch (batch_id),
  CONSTRAINT fk_staging_legacy_billing_invoice_batch FOREIGN KEY (batch_id) REFERENCES staging_import_batches(id),
  CONSTRAINT fk_staging_legacy_billing_invoice_target_subscription FOREIGN KEY (target_subscription_id) REFERENCES service_subscriptions(id),
  CONSTRAINT fk_staging_legacy_billing_invoice_target FOREIGN KEY (target_invoice_id) REFERENCES billing_invoices(id)
);

CREATE TABLE IF NOT EXISTS staging_legacy_billing_item_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  source_system ENUM('WEB_PSB') NOT NULL DEFAULT 'WEB_PSB',
  legacy_id VARCHAR(100) NULL,
  legacy_invoice_id VARCHAR(100) NULL,
  item_type VARCHAR(50) NULL,
  description VARCHAR(255) NULL,
  qty DECIMAL(12,2) NULL,
  unit_price DECIMAL(15,2) NULL,
  line_total DECIMAL(15,2) NULL,
  raw_payload LONGTEXT NULL,
  normalized_key VARCHAR(180) NULL,
  target_invoice_id BIGINT UNSIGNED NULL,
  target_item_id BIGINT UNSIGNED NULL,
  import_status ENUM('PENDING','MAPPED','VALID','INVALID','IMPORTED','SKIPPED') NOT NULL DEFAULT 'PENDING',
  validation_notes TEXT NULL,
  imported_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_staging_legacy_billing_item_batch (batch_id),
  CONSTRAINT fk_staging_legacy_billing_item_batch FOREIGN KEY (batch_id) REFERENCES staging_import_batches(id),
  CONSTRAINT fk_staging_legacy_billing_item_target_invoice FOREIGN KEY (target_invoice_id) REFERENCES billing_invoices(id),
  CONSTRAINT fk_staging_legacy_billing_item_target FOREIGN KEY (target_item_id) REFERENCES billing_invoice_items(id)
);

CREATE TABLE IF NOT EXISTS staging_legacy_billing_payment_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  source_system ENUM('WEB_PSB') NOT NULL DEFAULT 'WEB_PSB',
  legacy_id VARCHAR(100) NULL,
  legacy_invoice_id VARCHAR(100) NULL,
  payment_no VARCHAR(50) NULL,
  payment_date DATETIME NULL,
  amount DECIMAL(15,2) NULL,
  payment_method VARCHAR(50) NULL,
  reference_no VARCHAR(100) NULL,
  received_by_legacy_user VARCHAR(100) NULL,
  notes TEXT NULL,
  raw_payload LONGTEXT NULL,
  normalized_key VARCHAR(180) NULL,
  target_invoice_id BIGINT UNSIGNED NULL,
  target_payment_id BIGINT UNSIGNED NULL,
  import_status ENUM('PENDING','MAPPED','VALID','INVALID','IMPORTED','SKIPPED') NOT NULL DEFAULT 'PENDING',
  validation_notes TEXT NULL,
  imported_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_staging_legacy_billing_payment_batch (batch_id),
  CONSTRAINT fk_staging_legacy_billing_payment_batch FOREIGN KEY (batch_id) REFERENCES staging_import_batches(id),
  CONSTRAINT fk_staging_legacy_billing_payment_target_invoice FOREIGN KEY (target_invoice_id) REFERENCES billing_invoices(id),
  CONSTRAINT fk_staging_legacy_billing_payment_target FOREIGN KEY (target_payment_id) REFERENCES billing_payments(id)
);

CREATE TABLE IF NOT EXISTS staging_legacy_billing_collection_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  source_system ENUM('WEB_PSB') NOT NULL DEFAULT 'WEB_PSB',
  legacy_id VARCHAR(100) NULL,
  legacy_invoice_id VARCHAR(100) NULL,
  action_type VARCHAR(50) NULL,
  action_status VARCHAR(50) NULL,
  action_at DATETIME NULL,
  due_follow_up_at DATETIME NULL,
  handled_by_legacy_user VARCHAR(100) NULL,
  notes TEXT NULL,
  raw_payload LONGTEXT NULL,
  normalized_key VARCHAR(180) NULL,
  target_invoice_id BIGINT UNSIGNED NULL,
  target_collection_action_id BIGINT UNSIGNED NULL,
  import_status ENUM('PENDING','MAPPED','VALID','INVALID','IMPORTED','SKIPPED') NOT NULL DEFAULT 'PENDING',
  validation_notes TEXT NULL,
  imported_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_staging_legacy_billing_collection_batch (batch_id),
  CONSTRAINT fk_staging_legacy_billing_collection_batch FOREIGN KEY (batch_id) REFERENCES staging_import_batches(id),
  CONSTRAINT fk_staging_legacy_billing_collection_target_invoice FOREIGN KEY (target_invoice_id) REFERENCES billing_invoices(id),
  CONSTRAINT fk_staging_legacy_billing_collection_target FOREIGN KEY (target_collection_action_id) REFERENCES billing_collection_actions(id)
);

CREATE TABLE IF NOT EXISTS staging_legacy_inventory_item_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  source_system ENUM('GA') NOT NULL DEFAULT 'GA',
  legacy_id VARCHAR(100) NULL,
  legacy_category_id VARCHAR(100) NULL,
  legacy_unit_id VARCHAR(100) NULL,
  item_code VARCHAR(50) NULL,
  item_name VARCHAR(150) NULL,
  barcode VARCHAR(50) NULL,
  default_price DECIMAL(15,2) NULL,
  minimum_stock INT NULL,
  current_stock INT NULL,
  status_text VARCHAR(50) NULL,
  photo_path VARCHAR(255) NULL,
  raw_payload LONGTEXT NULL,
  normalized_key VARCHAR(180) NULL,
  mapped_category_code VARCHAR(50) NULL,
  mapped_unit_code VARCHAR(30) NULL,
  target_item_id BIGINT UNSIGNED NULL,
  import_status ENUM('PENDING','MAPPED','VALID','INVALID','IMPORTED','SKIPPED') NOT NULL DEFAULT 'PENDING',
  validation_notes TEXT NULL,
  imported_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_staging_legacy_inventory_item_batch (batch_id),
  CONSTRAINT fk_staging_legacy_inventory_item_batch FOREIGN KEY (batch_id) REFERENCES staging_import_batches(id),
  CONSTRAINT fk_staging_legacy_inventory_item_target FOREIGN KEY (target_item_id) REFERENCES inventory_items(id)
);

CREATE TABLE IF NOT EXISTS staging_legacy_network_odp_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  source_system ENUM('WEB_PSB') NOT NULL DEFAULT 'WEB_PSB',
  legacy_id VARCHAR(100) NULL,
  odp_code VARCHAR(50) NULL,
  odp_name VARCHAR(150) NULL,
  region_name VARCHAR(120) NULL,
  location_text TEXT NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  total_ports INT NULL,
  active_ports INT NULL,
  pole_status VARCHAR(80) NULL,
  is_active TINYINT(1) NULL,
  raw_payload LONGTEXT NULL,
  normalized_key VARCHAR(180) NULL,
  target_odp_id BIGINT UNSIGNED NULL,
  import_status ENUM('PENDING','MAPPED','VALID','INVALID','IMPORTED','SKIPPED') NOT NULL DEFAULT 'PENDING',
  validation_notes TEXT NULL,
  imported_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_staging_legacy_network_odp_batch (batch_id),
  KEY idx_staging_legacy_network_odp_target (target_odp_id),
  CONSTRAINT fk_staging_legacy_network_odp_batch FOREIGN KEY (batch_id) REFERENCES staging_import_batches(id),
  CONSTRAINT fk_staging_legacy_network_odp_target FOREIGN KEY (target_odp_id) REFERENCES network_odp(id)
);

CREATE TABLE IF NOT EXISTS staging_legacy_inventory_movement_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  source_system ENUM('GA') NOT NULL DEFAULT 'GA',
  movement_source ENUM('BARANG_MASUK','BARANG_KELUAR','ADJUSTMENT') NOT NULL,
  legacy_id VARCHAR(100) NULL,
  legacy_item_id VARCHAR(100) NULL,
  reference_no VARCHAR(50) NULL,
  movement_type VARCHAR(30) NULL,
  qty INT NULL,
  unit_price DECIMAL(15,2) NULL,
  movement_at DATETIME NULL,
  assignee_name VARCHAR(120) NULL,
  notes TEXT NULL,
  raw_payload LONGTEXT NULL,
  normalized_key VARCHAR(180) NULL,
  target_item_id BIGINT UNSIGNED NULL,
  target_work_order_id BIGINT UNSIGNED NULL,
  target_movement_id BIGINT UNSIGNED NULL,
  import_status ENUM('PENDING','MAPPED','VALID','INVALID','IMPORTED','SKIPPED') NOT NULL DEFAULT 'PENDING',
  validation_notes TEXT NULL,
  imported_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_staging_legacy_inventory_movement_batch (batch_id),
  CONSTRAINT fk_staging_legacy_inventory_movement_batch FOREIGN KEY (batch_id) REFERENCES staging_import_batches(id),
  CONSTRAINT fk_staging_legacy_inventory_movement_target_item FOREIGN KEY (target_item_id) REFERENCES inventory_items(id),
  CONSTRAINT fk_staging_legacy_inventory_movement_target_work_order FOREIGN KEY (target_work_order_id) REFERENCES service_work_orders(id),
  CONSTRAINT fk_staging_legacy_inventory_movement_target FOREIGN KEY (target_movement_id) REFERENCES inventory_stock_movements(id)
);

CREATE TABLE IF NOT EXISTS staging_legacy_employee_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  source_system ENUM('FINANCE') NOT NULL DEFAULT 'FINANCE',
  legacy_id VARCHAR(100) NULL,
  employee_code VARCHAR(50) NULL,
  full_name VARCHAR(150) NULL,
  department_text VARCHAR(120) NULL,
  position_name VARCHAR(120) NULL,
  employment_status VARCHAR(50) NULL,
  join_date DATE NULL,
  base_salary DECIMAL(15,2) NULL,
  phone VARCHAR(30) NULL,
  whatsapp VARCHAR(30) NULL,
  raw_payload LONGTEXT NULL,
  normalized_key VARCHAR(180) NULL,
  mapped_division_code VARCHAR(30) NULL,
  target_employee_id BIGINT UNSIGNED NULL,
  import_status ENUM('PENDING','MAPPED','VALID','INVALID','IMPORTED','SKIPPED') NOT NULL DEFAULT 'PENDING',
  validation_notes TEXT NULL,
  imported_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_staging_legacy_employee_batch (batch_id),
  CONSTRAINT fk_staging_legacy_employee_batch FOREIGN KEY (batch_id) REFERENCES staging_import_batches(id),
  CONSTRAINT fk_staging_legacy_employee_target FOREIGN KEY (target_employee_id) REFERENCES hr_employees(id)
);

CREATE TABLE IF NOT EXISTS staging_legacy_attendance_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  source_system ENUM('FINANCE') NOT NULL DEFAULT 'FINANCE',
  legacy_id VARCHAR(100) NULL,
  legacy_employee_id VARCHAR(100) NULL,
  attendance_date DATE NULL,
  check_in DATETIME NULL,
  check_out DATETIME NULL,
  attendance_status VARCHAR(50) NULL,
  overtime_hours DECIMAL(6,2) NULL,
  locked_by_admin TINYINT(1) NULL,
  raw_payload LONGTEXT NULL,
  normalized_key VARCHAR(180) NULL,
  target_employee_id BIGINT UNSIGNED NULL,
  target_attendance_id BIGINT UNSIGNED NULL,
  import_status ENUM('PENDING','MAPPED','VALID','INVALID','IMPORTED','SKIPPED') NOT NULL DEFAULT 'PENDING',
  validation_notes TEXT NULL,
  imported_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_staging_legacy_attendance_batch (batch_id),
  CONSTRAINT fk_staging_legacy_attendance_batch FOREIGN KEY (batch_id) REFERENCES staging_import_batches(id),
  CONSTRAINT fk_staging_legacy_attendance_target_employee FOREIGN KEY (target_employee_id) REFERENCES hr_employees(id),
  CONSTRAINT fk_staging_legacy_attendance_target FOREIGN KEY (target_attendance_id) REFERENCES hr_attendance(id)
);

CREATE TABLE IF NOT EXISTS staging_legacy_salary_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  source_system ENUM('FINANCE') NOT NULL DEFAULT 'FINANCE',
  legacy_id VARCHAR(100) NULL,
  legacy_employee_id VARCHAR(100) NULL,
  payroll_month TINYINT UNSIGNED NULL,
  payroll_year SMALLINT UNSIGNED NULL,
  base_salary DECIMAL(15,2) NULL,
  attendance_allowance DECIMAL(15,2) NULL,
  overtime_amount DECIMAL(15,2) NULL,
  performance_bonus DECIMAL(15,2) NULL,
  position_allowance DECIMAL(15,2) NULL,
  loan_deduction DECIMAL(15,2) NULL,
  total_income DECIMAL(15,2) NULL,
  total_deduction DECIMAL(15,2) NULL,
  net_salary DECIMAL(15,2) NULL,
  released_at DATETIME NULL,
  raw_payload LONGTEXT NULL,
  normalized_key VARCHAR(180) NULL,
  target_employee_id BIGINT UNSIGNED NULL,
  target_salary_slip_id BIGINT UNSIGNED NULL,
  import_status ENUM('PENDING','MAPPED','VALID','INVALID','IMPORTED','SKIPPED') NOT NULL DEFAULT 'PENDING',
  validation_notes TEXT NULL,
  imported_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_staging_legacy_salary_batch (batch_id),
  CONSTRAINT fk_staging_legacy_salary_batch FOREIGN KEY (batch_id) REFERENCES staging_import_batches(id),
  CONSTRAINT fk_staging_legacy_salary_target_employee FOREIGN KEY (target_employee_id) REFERENCES hr_employees(id),
  CONSTRAINT fk_staging_legacy_salary_target FOREIGN KEY (target_salary_slip_id) REFERENCES hr_salary_slips(id)
);

CREATE TABLE IF NOT EXISTS staging_legacy_loan_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  source_system ENUM('FINANCE') NOT NULL DEFAULT 'FINANCE',
  legacy_id VARCHAR(100) NULL,
  legacy_employee_id VARCHAR(100) NULL,
  loan_type VARCHAR(50) NULL,
  amount DECIMAL(15,2) NULL,
  monthly_installment DECIMAL(15,2) NULL,
  loan_date DATE NULL,
  loan_status VARCHAR(50) NULL,
  description TEXT NULL,
  raw_payload LONGTEXT NULL,
  normalized_key VARCHAR(180) NULL,
  target_employee_id BIGINT UNSIGNED NULL,
  target_loan_id BIGINT UNSIGNED NULL,
  import_status ENUM('PENDING','MAPPED','VALID','INVALID','IMPORTED','SKIPPED') NOT NULL DEFAULT 'PENDING',
  validation_notes TEXT NULL,
  imported_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_staging_legacy_loan_batch (batch_id),
  CONSTRAINT fk_staging_legacy_loan_batch FOREIGN KEY (batch_id) REFERENCES staging_import_batches(id),
  CONSTRAINT fk_staging_legacy_loan_target_employee FOREIGN KEY (target_employee_id) REFERENCES hr_employees(id),
  CONSTRAINT fk_staging_legacy_loan_target FOREIGN KEY (target_loan_id) REFERENCES hr_loans(id)
);
